#pragma once


 #define DEBUG_SERVER
// #define MODE_PENALTY
// #define CHECK_MODE_FROM_FILE


// Config of AI character
#define CHARACTER_SIZE		300
#define CHARACTER_SPEED		30
#define CHARACTER_BLOOD		100

// THE AREA AI CAN SEE OR HEAR ENEMY...
#define VISIBLE_RANGE		3600
#define LISTENABLE_RANGE	5000

// MAP SIZE
#define MAP_SIZE			14000
#define WIDTH				14400
#define HEIGH				9600
#define OFFSET_X			100
#define OFFSET_Y			100
#define RADIUS_CENTER		1350

// USE RANGE
#define PISTAL_RANGE		5000
#define RIFLE_RANGE			6500
#define GRENADE_RANGE		4000

// BULLET SPEED
#define	PISTAL_BULLET_SPEED	5000
#define REFILE_BULLET_SPEED 5000
#define	GRENADE_SPEED		1500

// MAX VALUE OF BULLET IN ARMORY
#define PISTAL_MAX_NUM		50		//It's infinity but you just need to show the bullet visible in map
#define RIFLE_MAX_NUM		30
#define	GRENADE_MAX_NUM		5



#define TIME				3000	// 3000 turn

#define MAX_FB 5

#define ENABLE_RANDOM_FORCE 4
#define ENABLE_RANDOM_DIRECTION 3

#define R_BALL 1
#define R_FB 2

#define SPEED_FB 
#define RAD_TO_SHOOT 200
#define MAX_FORCE 100
#define GOALWIDTH 3000
#define TIME_PER_MATCH 5*60
#define OFF_GOAL 50
#define FILE_INPUT_STEP 4
#define TURN_PER_MATCH_ORIGINAL 500
#define PLAYER_SPEED 300
#define TURN_EXTRA_MATCH_ORIGINAL 300


#define BALL_SCALE_SPEED 10
#define BALL_ACC_SPEED 120
#define DRAW_SCALE 20
#define PENALTY_POINT 3200
#define NUMBER_PENALTY 10
#define EXTRA_PENALTY 10
#define TURN_PER_PEN 5
